# -*- coding: utf-8 -*-
"""CarDamageDetection_HybridML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjDpJ3391ivwZJ7gbwvUvbhp-ZysYIL-
"""



print("Car Damage Detection")

# Import necessary libraries
import os
import zipfile
import requests

# URL to your dataset zip file in the GitHub repository
dataset_url = 'https://raw.githubusercontent.com/rafdimilzano/data/main/cdadataset.zip'  # Change this URL to your dataset location

# Download the dataset
dataset_zip_path = 'cdadataset.zip'
response = requests.get(dataset_url)

# Save the zip file locally
with open(dataset_zip_path, 'wb') as file:
    file.write(response.content)

# Unzip the dataset
with zipfile.ZipFile(dataset_zip_path, 'r') as zip_ref:
    zip_ref.extractall('dataset')  # Extract the dataset into the 'dataset' folder

# Check the unzipped folder structure
os.listdir('dataset')

import os
import math
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random as python_random
import tensorflow as tf
import seaborn as sns
import math
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import cv2
from tensorflow.keras.callbacks import ModelCheckpoint
from  tensorflow.keras.callbacks import EarlyStopping
from keras import backend as K
from tensorflow.keras.applications import VGG16
from tensorflow.keras.layers import Flatten, Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

# np.random.seed(42)
# tf.random.set_seed(42)

# Set dataset paths
train_dir = 'dataset/training'    # Path to the Training set
val_dir = 'dataset/validation'    # Path to the Validation set
image_size = (224, 224)  # Resize images to 190x190
batch_size = 32

# Image augmentation for the training set to improve generalization
train_datagen = ImageDataGenerator(rescale=1.0/255)

# No augmentation for validation data, only rescaling
val_datagen = ImageDataGenerator(rescale=1.0/255)

# Loading training data from the structured directories
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical'
)

# Loading validation data from the structured directories
validation_generator = val_datagen.flow_from_directory(
    val_dir,
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical'
)

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

# Load ResNet50 without the top layer
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# Add new layers for transfer learning
x = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)
x = Dense(1024, activation='relu')(x)
x = Dense(train_generator.num_classes, activation='softmax')(x)

# Create the new model
model = Model(inputs=base_model.input, outputs=x)

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

print('CNN model set up successfully.')

from tensorflow.keras.callbacks import ModelCheckpoint

# Set training options
checkpoint = ModelCheckpoint('best_model.keras', monitor='val_accuracy', save_best_only=True, mode='max')
callbacks_list = [checkpoint]

model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=1e-4),
              loss='categorical_crossentropy', metrics=['accuracy'])

print('Training options set.')

# Train the model
history = model.fit(
    train_generator,
    steps_per_epoch=20,
    epochs=10,
    validation_data=validation_generator,
    callbacks=callbacks_list,
    verbose=1
)

print('Model training completed.')

# Predictions on validation dataset
Y_pred_cnn = model.predict(validation_generator)
Y_pred_classes = Y_pred_cnn.argmax(axis=-1)
Y_true = validation_generator.classes

# Performance evaluation (CNN)
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy_cnn = accuracy_score(Y_true, Y_pred_classes)
precision_cnn = precision_score(Y_true, Y_pred_classes, average='macro')
recall_cnn = recall_score(Y_true, Y_pred_classes, average='macro')
f1_cnn = f1_score(Y_true, Y_pred_classes, average='macro')

print(f'CNN Accuracy: {accuracy_cnn * 100:.2f}%')
print(f'CNN Precision: {precision_cnn:.2f}')
print(f'CNN Recall: {recall_cnn:.2f}')
print(f'CNN F1 Score: {f1_cnn:.2f}')

from sklearn.neighbors import KNeighborsClassifier
import numpy as np

# Feature extraction (you can use a pre-trained model to extract features)
def extract_features(generator, model):
    features = model.predict(generator)
    return np.reshape(features, (features.shape[0], -1))

train_features = extract_features(train_generator, base_model)
validation_features = extract_features(validation_generator, base_model)

# Train k-NN
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(train_features, train_generator.classes)

# Predictions on validation dataset
Y_pred_knn = knn.predict(validation_features)

# Performance evaluation (k-NN)
accuracy_knn = accuracy_score(Y_true, Y_pred_knn)
precision_knn = precision_score(Y_true, Y_pred_knn, average='macro')
recall_knn = recall_score(Y_true, Y_pred_knn, average='macro')
f1_knn = f1_score(Y_true, Y_pred_knn, average='macro')

print(f'k-NN Accuracy: {accuracy_knn * 100:.2f}%')
print(f'k-NN Precision: {precision_knn:.2f}')
print(f'k-NN Recall: {recall_knn:.2f}')
print(f'k-NN F1 Score: {f1_knn:.2f}')

from sklearn.svm import SVC

# Train SVM model
svm = SVC(kernel='linear')
svm.fit(train_features, train_generator.classes)

# Predictions on validation dataset
Y_pred_svm = svm.predict(validation_features)

# Performance evaluation (SVM)
accuracy_svm = accuracy_score(Y_true, Y_pred_svm)
precision_svm = precision_score(Y_true, Y_pred_svm, average='macro')
recall_svm = recall_score(Y_true, Y_pred_svm, average='macro')
f1_svm = f1_score(Y_true, Y_pred_svm, average='macro')

print(f'SVM Accuracy: {accuracy_svm * 100:.2f}%')
print(f'SVM Precision: {precision_svm:.2f}')
print(f'SVM Recall: {recall_svm:.2f}')
print(f'SVM F1 Score: {f1_svm:.2f}')

def evaluate_performance(Y_true, Y_pred, categories):
    accuracy = accuracy_score(Y_true, Y_pred)
    precision = precision_score(Y_true, Y_pred, average='macro')
    recall = recall_score(Y_true, Y_pred, average='macro')
    f1 = f1_score(Y_true, Y_pred, average='macro')
    return accuracy, precision, recall, f1