# -*- coding: utf-8 -*-
"""CarDamageDetection_ResNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nv5NDSRAxEovH_FJENUMV7Fb7FR-R0HW
"""

print("Car Damage Detection")

# Import necessary libraries
import os
import zipfile
import requests

# URL to your dataset zip file in the GitHub repository
dataset_url = 'https://raw.githubusercontent.com/rafdimilzano/data/main/cdadataset.zip'  # Change this URL to your dataset location

# Download the dataset
dataset_zip_path = 'cdadataset.zip'
response = requests.get(dataset_url)

# Save the zip file locally
with open(dataset_zip_path, 'wb') as file:
    file.write(response.content)

# Unzip the dataset
with zipfile.ZipFile(dataset_zip_path, 'r') as zip_ref:
    zip_ref.extractall('dataset')  # Extract the dataset into the 'dataset' folder

# Check the unzipped folder structure
os.listdir('dataset')

import os
import math
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random as python_random
import tensorflow as tf
import seaborn as sns
import math
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import cv2
from tensorflow.keras.callbacks import ModelCheckpoint
from  tensorflow.keras.callbacks import EarlyStopping
from keras import backend as K
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Flatten, Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

np.random.seed(42)
tf.random.set_seed(42)

# Set dataset paths
train_dir = 'dataset/training'    # Path to the Training set
val_dir = 'dataset/validation'    # Path to the Validation set
image_size = (190, 190)  # Resize images to 190x190
batch_size = 32

# Image augmentation for the training set to improve generalization
train_datagen = ImageDataGenerator(
    rescale=1.0/255,            # Rescale pixel values to [0, 1]
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

# No augmentation for validation data, only rescaling
val_datagen = ImageDataGenerator(rescale=1.0/255)

# Loading training data from the structured directories
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical'
)

# Loading validation data from the structured directories
validation_generator = val_datagen.flow_from_directory(
    val_dir,
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical'
)

resnet_base_model = ResNet50(
    include_top=False,
    weights='imagenet',
    input_shape=(190, 190, 3)
)

for layer in resnet_base_model.layers:
    layer.trainable = False

from tensorflow.keras import layers
num_classes = 3

# 3. Fine-tune the Model
# model = Sequential()
# model.add(base_model)
# # model.add(Flatten())
# # model.add(Dense(512, activation='relu'))
# # model.add(Dropout(0.5))
# # model.add(Dense(num_classes, activation='softmax'))

# model.add(GlobalAveragePooling2D())

# model.add(Flatten())
# model.add(Dense(256, activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(256, activation='relu'))
# model.add(Dropout(0.5))

# #
# model.add(Dense(num_classes, activation='softmax'))

# resnetmodel = Sequential([
#     resnet_base_model,
#     Flatten(),
#     Dense(256, activation='relu'),
#     Dropout(0.5),
#     Dense(num_classes, activation='softmax')  # binary classification, so 1 neuron with sigmoid activation
# ])
# vggmodel = tf.keras.models.Model(resnetmodel.input, predictions)

last_output = resnet_base_model.output
x = layers.Flatten()(last_output)
x = layers.Dense(256, activation='relu')(x)
x = layers.Dropout(0.5)(x)
predictions = layers.Dense(num_classes, activation='softmax')(x)

resnetmodel = tf.keras.models.Model(resnet_base_model.input, predictions)

resnetmodel.compile(optimizer='adam',
              loss='CategoricalCrossentropy',
              metrics=['accuracy'])

resnetmodel.summary()

# Try importing the callback from tensorflow.keras.callbacks
from tensorflow.keras.callbacks import EarlyStopping

# Define a callback to stop training when accuracy reaches a certain threshold
early_stopping = EarlyStopping(monitor='val_loss', patience=5, min_delta=0.005) #Example values for patience and min_delta

resnethist = resnetmodel.fit(
    train_generator,
    steps_per_epoch=40,
    epochs=20,
    validation_data=validation_generator,
    validation_steps=10,
    callbacks=[early_stopping]
    )

# Plot the training history for accuracy
plt.plot(resnethist.history['accuracy'], label='train accuracy')
plt.plot(resnethist.history['val_accuracy'], label='val accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

# Evaluate the model on validation data
val_loss, val_acc = resnetmodel.evaluate(validation_generator)
print(f"Validation Accuracy: {val_acc*100:.2f}%")

def classify_image(image_path, model):
    img = tf.keras.preprocessing.image.load_img(image_path, target_size=image_size)
    img_array = tf.keras.preprocessing.image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0  # Scale the image

    prediction = model.predict(img_array)
    class_labels = ['Minor', 'Moderate', 'Severe']
    return class_labels[np.argmax(prediction)]

# Test classification
# test_image = 'path_to_test_image'
# classification = classify_image(test_image, model)
# print(f"Damage Severity: {classification}")