# -*- coding: utf-8 -*-
"""CarDamageDetection_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P70MakpVNfxME_59dRiy9O2SiFqVd-MR
"""

print("Car Damage Detection")

# Import necessary libraries
import os
import zipfile
import requests

# URL to your dataset zip file in the GitHub repository
dataset_url = 'https://raw.githubusercontent.com/rafdimilzano/data/main/cdadataset.zip'  # Change this URL to your dataset location

# Download the dataset
dataset_zip_path = 'cdadataset.zip'
response = requests.get(dataset_url)

# Save the zip file locally
with open(dataset_zip_path, 'wb') as file:
    file.write(response.content)

# Unzip the dataset
with zipfile.ZipFile(dataset_zip_path, 'r') as zip_ref:
    zip_ref.extractall('dataset')  # Extract the dataset into the 'dataset' folder

# Check the unzipped folder structure
os.listdir('dataset')

import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.model_selection import train_test_split
from tensorflow import keras
import matplotlib.pyplot as plt

# Set dataset paths
train_dir = 'dataset/training'    # Path to the Training set
val_dir = 'dataset/validation'    # Path to the Validation set
image_size = (224, 224)  # Resize images to 224x224
batch_size = 32

# Image augmentation for the training set to improve generalization
train_datagen = ImageDataGenerator(
    rescale=1.0/255,            # Rescale pixel values to [0, 1]
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

# No augmentation for validation data, only rescaling
val_datagen = ImageDataGenerator(rescale=1.0/255)

# Loading training data from the structured directories
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical'
)

# Loading validation data from the structured directories
validation_generator = val_datagen.flow_from_directory(
    val_dir,
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical'
)

print(train_generator)

num_classes = 3  # Since we have three classes: minor, moderate, and severe

# Build the CNN model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),
    MaxPool2D(pool_size=(2, 2)),

    Conv2D(64, (3, 3), activation='relu'),
    MaxPool2D(pool_size=(2, 2)),

    Conv2D(128, (3, 3), activation='relu'),
    MaxPool2D(pool_size=(2, 2)),

    Conv2D(256, (3, 3), activation='relu'),
    MaxPool2D(pool_size=(2, 2)),

    Flatten(),

    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax')  # 3 output classes
])


# Compile the model
model.compile(optimizer=keras.optimizers.Adam(1e-4),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Set up early stopping and model checkpoint callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
checkpoint = ModelCheckpoint('car_damage_model.keras', save_best_only=True, monitor='val_accuracy')

# Train the model
history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=20,
    callbacks=[early_stopping, checkpoint]
)

# Plot the training history for accuracy
plt.plot(history.history['accuracy'], label='train accuracy')
plt.plot(history.history['val_accuracy'], label='val accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

# Evaluate the model on validation data
val_loss, val_acc = model.evaluate(validation_generator)
print(f"Validation Accuracy: {val_acc*100:.2f}%")

from sklearn.metrics import classification_report, confusion_matrix

# Generate predictions and true labels for the classification report
y_pred = model.predict(validation_generator)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = validation_generator.classes
class_labels = list(validation_generator.class_indices.keys())

# Print the classification report
print("Classification Report:")
print(classification_report(y_true, y_pred_classes, target_names=class_labels, digits=3))

print(model.summary())

dot_img_file = '/model_cnn.png'
keras.utils.plot_model(model, to_file=dot_img_file, show_shapes=True, dpi=100)

def classify_image(image_path, model):
    img = tf.keras.preprocessing.image.load_img(image_path, target_size=image_size)
    img_array = tf.keras.preprocessing.image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0  # Scale the image

    prediction = model.predict(img_array)
    class_labels = ['Minor', 'Moderate', 'Severe']
    return class_labels[np.argmax(prediction)]

# Test classification
# test_image = 'path_to_test_image'
# classification = classify_image(test_image, model)
# print(f"Damage Severity: {classification}")